### ISSUE TITLE
Cancelling an ongoing animation does not complete animation in progress

### ISSUE THREAD

**Issue by atotic** [PolymerElements/neon-animation#81] opened 2015-09-30 04:16 UTC
This bug can be demonstrated on neon-animation-demo pages. Go to 'declarative' demo, and flip quickly through the pages. Cancelled animations will cause a lot of blank-page animations.

Reason:
- at the beggining of every animation `neon-animated-pages._selectedChanged` inserts opaque-animation.
- `opaque-animation.configure` sets pages's opacity to 0. It usually removes this flag in `opaque-animation.complete`, which gets called by `animation.onfinish` callback.
- `neon-animated-pages._selectedChanged` will interrupt ongoing animation if selection changes, and this happens when you flip rapidly.
- interrupted animation never gets its onfinish callback called
- so opaque-animation never resets the opacity flag back to original value, and page remains opaque until it is animated again.

The fix:
- according to web animation standard, http://w3c.github.io/web-animations/#the-animation-interface, there should be an oncancel event fired when animation is cancelled. web-animations-js does not fire this event.
- neon-animated-pages also does not listen to cancel event
- you could fix this in your code right now with the workaround I use below:

The workaround:
In my code, I call the callback manually before cancellation, and that makes everything run well.
```
        var f = this.lazy._player.onfinish;
        this.lazy._player.onfinish = function() {};
        f.apply(this.lazy._player);
```

Might be related to #71 and #74

**Comment by taylorstine** [comment] 2015-10-12 23:10
commenting out these lines also fixed the issue for me https://github.com/PolymerElements/neon-animation/blob/master/neon-animated-pages.html#L207-L210

**Comment by hawkett** [comment] 2015-10-14 01:35
If this is a duplicate of #71 and #74, then there's a 1 line PR (#75) ready to go that fixes those issues. Is there anything preventing that from being merged?

**Comment by atotic** [comment] 2015-10-16 23:43
The PR does not fix this one. That PR fixed "my mouse clicks don't work". The real fix for this one needs web-animations polyfill to implement cancel event. I've suggested the workaround, but Polymer team has pull, and it would be better to fix web-animations cancel event, and fix it for everyone.

**Comment by cdata** [comment] 2015-12-10 21:28
Thanks for reporting @atotic - I will take a look.

**Closed** 2016-05-16 06:14 UTC
Labels: bug, p1 - backlog
