### ISSUE TITLE
Slide Up Animation in Neon Animated Pages

### ISSUE THREAD

**Issue by oliver92** [PolymerElements/neon-animation#120] opened 2015-12-14 14:36 UTC
Hi,
Im trying to add animation to neon-animated-pages like so:

```html
<neon-animated-pages animate-initial-selection="true" entry-animation="slide-up-animation" attr-for-selected="data-route" selected="{{route}}" exit-animation="fade-out-animation">
     <neon-animatable data-route="home">
         <home-page></home-page>
     </neon-animatable> 
</neon-animated-pages>
```

This works fine if i change the slide-up-animation to scale-up for example. Every other animation works except this the slide-up-animation.

I have included the animation itself, and any other i tryed. My neon-animation elements are version 1.0.8

Is this a polymer bug, or do i have to do something different when using slide-up-animation?

**Comment by cdata** [comment] 2016-02-04 20:09
Hi, can you provide a test case demonstrating your problem?

Please review our [contribution guidelines](../blob/master/CONTRIBUTING.md) for more details on filing issues!

**Comment by ozasadnyy** [comment] 2016-02-06 19:46
@cdata I can.

The `neon-animated-pages` doesn't animate `slide-up-animation` and `slide-down-animation`

## Expected outcome

Container slides up on entry and slide down on exit

## Actual outcome

Pages change without animation

## Steps to reproduce

```
<paper-tabs selected="{{_selected}}">
   <paper-tab>Page 1</paper-tab>
   <paper-tab>Page 2</paper-tab>
</paper-tabs>

<neon-animated-pages entry-animation="slide-up-animation" selected="{{_selected}}" exit-animation="fade-out-animation">
   <neon-animatable>
         <div>Page 1</div>
   </neon-animatable> 
   <neon-animatable>
         <div>Page 2</div>
   </neon-animatable> 
</neon-animated-pages>

```

**Comment by oliver92** [comment] 2016-02-07 23:05
@cdata I think it has something to do with the height, and when its set to 100%, i have noticed when there is a height of 100% on the parent node, the animations wont work.

**Comment by NicolasRannou** [comment] 2016-05-05 15:33
+1

**Comment by NicolasRannou** [comment] 2016-05-12 07:39
FYI - I am trying to animate pages within app-layout, all animations including slide left-right work.
Only issue is slide up/down.

**Comment by dstockwell** [comment] 2016-05-12 09:15
Unfortunately the content of `<neon-animated-pages>` is styled as `position: absolute` (so that multiple pages can be visible at the same time without affecting each other's positions). This means the computed height is usually `0px`. Since `slide-up-animation` and `slide-down-animation` transform the element using percentages, they end up transforming the element between `0px` and `0px`...

The problem as stated can be avoided by ensuring that `<neon-animated-pages>` has the appropriate computed height by styling it directly, or laying it out using something like flexbox.

**Comment by NicolasRannou** [comment] 2016-05-12 09:18
Thanks for the clear explanation - will look into it. Should only <neon-animated-pages> have the height appropriately computed or the inner pages to be animated too?

**Comment by oliver92** [comment] 2016-05-12 09:24
Yup its the parent height :)

**Comment by dstockwell** [comment] 2016-05-13 00:41
> Thanks for the clear explanation - will look into it. Should only `<neon-animated-pages>` have the height appropriately computed or the inner pages to be animated too?

Just  `<neon-animated-pages>` should be fine, the size of the inner pages doesn't impact how `slide-up/down-animation` functions.

**Comment by dstockwell** [comment] 2016-05-13 00:42
Closing this out, I don't think this can be fixed in `neon-animated-pages` or the individual animations.

**Closed by dstockwell** 2016-05-13 00:42 UTC
Labels: p2 - icebox, pending-response, question
