### ISSUE TITLE
How to use animate-initial-selection

### ISSUE THREAD

**Issue by BartKoppelmans** [PolymerElements/neon-animation#105] opened 2015-11-18 20:44 UTC
Hello,

I am not sure how to use `animate-initial-selection` in the neon-animated-pages element.

I have the following setup:

``` HTML
    <neon-animated-pages id="pages" selected="0" animate-initial-selection>

      <letter-holder-page></letter-holder-page>

      <letter-detail-page></letter-detail-page>

    </neon-animated-pages>
```

My `letter-holder-page` and `letter-detail-page` share an element and have hero-animations to share the element. Is my use of `animate-initial-selection` correct? And if so, why do I get an error that says: 

```
Uncaught TypeError: Cannot read property 'getAnimationConfig' of undefined
```

Bart

**Comment by dsschnau** [comment] 2015-11-24 22:47
Hey Bart,

I _think_ you're using that property right (though i haven't used it myself). But the error you're seeing about `getAnimationConfig` probably indicates that `<letter-holder-page>` doesn't implement `Polymer.NeonAnimatableBehavior` Or one of the other behaviors that expose `animationConfig`. Can you verify that?

**Comment by BartKoppelmans** [comment] 2015-11-25 07:13
Hey Dan,

It does, it implements  `Polymer.NeonSharedElementAnimatableBehavior`. Everything is working correctly without the `animate-initial-selection`. With, however, it doesn't.

**Comment by cdata** [comment] 2015-12-10 23:23
Possibly related bug https://github.com/PolymerElements/neon-animation/issues/112

**Comment by cdata** [comment] 2016-02-03 23:25
Closing as a dupe of #112.

**Closed by cdata** 2016-02-03 23:25 UTC
Labels: bug
