### ISSUE TITLE
neon animation run  when there is an iron-select on grand child element 

### ISSUE THREAD

**Issue by pedrule** [PolymerElements/neon-animation#164] opened 2016-04-09 07:53 UTC
### Description
I can't solve this issue and I don't understand what happen. I created custom pages in neon animated pages with a selected properties. But the animation run with any pressed on any element inside the custom elements which trigger iron-select event, no matter the selected property change or not.

### Expected outcome

transition between pages when selected property change

### Actual outcome

transition run with any tap on any selectable element

### Browsers Affected

- [ ] Chrome

**Comment by pedrule** [comment] 2016-04-09 11:06
I fix the issue by re-installing older version of neon-animation ( 1.0.0), it seems tobe the last version which have a problem with the bubble behavior from iron-select event of the childs of the animatable components.

**Comment by fenerlee1907** [comment] 2016-04-12 08:45
I think it is a big problem and has to be solved. I also face the same problem and it triggers a lot of problems. 

I created an element which uses iron-selector and put my element inside neon-animated-pages. When I select something inside my element, this triggers iron-select event of neon-animated-pages. It is very strange.

**Comment by fenerlee1907** [comment] 2016-04-12 10:06
There is also another issue about this:

https://github.com/PolymerElements/neon-animation/issues/146

**Comment by samuelli** [comment] 2016-04-21 03:04
Duplicate of #146

**Closed by samuelli** 2016-04-21 03:04 UTC
Labels: duplicate
