### ISSUE TITLE
Animated pages overlapped each other.

### ISSUE THREAD

**Issue by motss** [PolymerElements/neon-animation#46] opened 2015-06-28 12:06 UTC
The pages overlapped as seen in the image. 

![Page 1 and Page 2 overlapped](https://cloud.githubusercontent.com/assets/10607759/8445373/d554d6ac-1fce-11e5-9091-8b67db95efb6.png)

**Comment by morethanreal** [comment] 2015-06-30 00:00
@motss The image is broken for me. How do you reproduce the issue?

**Comment by motss** [comment] 2015-06-30 00:26
@morethanreal Please try again if you can see the image.

**Comment by motss** [comment] 2015-07-01 01:03
I used it with paper-tabs. 
Steps to reproduce error:
- click on each tabs once to see if it is showing the correct content.
- click on the second tab (or Page 2) several times.
- then click on any other tab like the last tab (Page 3). The overlap will occur.

**Comment by solomongracio** [comment] 2015-10-14 09:20
Any update on this ? I am also facing the same issue.

**Comment by hawkett** [comment] 2015-10-14 18:54
This is probably a duplicate of #71 and #74. #75 is intended to fix this problem, but has been waiting nearly a month to merge unfortunately.

**Comment by cdata** [comment] 2015-12-10 20:14
Closing as fixed by #75.

**Closed by cdata** 2015-12-10 20:14 UTC
Labels: bug
