### ISSUE TITLE
Rapidly changing pages can lose track of 'neon-animating' class

### ISSUE THREAD

**Issue by atotic** [PolymerElements/neon-animation#74] opened 2015-09-17 20:47 UTC
If you rapidly switch between multiple pages, 'neon-animating' flag can get stuck on one of your pages. This causes the entire page to be unclickable.

The cause is that previous animation gets cancelled before it even starts, so _squelchNextFinishEvent flag does not get cleared by _neonAnimationFinish.

I have a simple fix, filing this to have a bug to reference.

**Comment by johnheroy** [comment] 2015-09-17 22:08
+1, also seeing this issue.

**Comment by hawkett** [comment] 2015-09-18 19:20
Is this a duplicate of #71?

**Closed** 2015-10-16 20:58 UTC
Labels: duplicate
