### ISSUE TITLE
can't use flex inside neon-animated-pages

### ISSUE THREAD

**Issue by zishanj** [PolymerElements/neon-animation#15] opened 2015-05-31 18:00 UTC
I am using `neon-animated-pages` to animate the page. I have set it's height to 100%. I am using `div` inside it with `background-image`. But the height of div doesn't cover the entire browser height and is limited to it's internal content only. I have tried using `flex` with div but that also doesn't work. If I use this div outside of `neon-animated-pages` then it flexes well and cover the entire browser height.

What's going wrong inside `neon-animated-pages`?

**Comment by yo3jones** [comment] 2015-06-01 00:45
I am having a similar issue, but in my case I am setting an element internal to the page with `fix`.  When I do this, the page will never be shown.

**Comment by zishanj** [comment] 2015-06-01 06:48
Actually I am using `paper-toolbar` also on the page due to which I can't use `fit`. Here is sample how I am using `neon-animated-pages`:

    <neon-animated-pages id="pages" selected="0" class="flex">
      <my-card>
       <paper-toolbar>
        <paper-icon-button icon="menu"></paper-icon-button>
        <span title>Toolbar</span>
        <paper-icon-button icon="refresh"></paper-icon-button>
        <paper-icon-button icon="add">+</paper-icon-button>
       </paper-toolbar>
       <div id="bg" class="flex">
        <p>test</p>
       </div>
      </my-card>
    </neon-animated-pages>

I have checked that when using `flex` on `neon-animated-pages` it does makes it's height and the child element `my-card` to the entire browser but the internal `div` with `flex` doesn't works and is limited to it's internal content only.

**Comment by zishanj** [comment] 2015-06-01 07:05
Did some more experiment on it. What I came to know is, this `flex: 1` can only be used in parent and never works for child elements. As a temporary workaround, I have used `calc` on child `div` height in css like this:

    height: calc(100% - 64px);

where 64px is the fixed height of `paper-toolbar` and it works fine. But I am still curious to use `flex` instead of this custom height. :(

**Comment by morethanreal** [comment] 2015-06-01 18:31
@zishanj It seems like in your example, you're using `flex` on a child of `<my-card>`. Is `<my-card>` a flex container? `flex` makes the element a flex item, and is only meaningful inside a flex container (e.g. something with `class="layout horizontal"` or `class="`layout vertical`.

**Comment by zishanj** [comment] 2015-06-01 18:43
@morethanreal `my-card` is not flex but I have used `neon-animated-pages` as a `flex`. But I have inspected the layout of `my-card` and it's giving full length of the browser. Still this `div` is limited to content and `flex` doesn't works on it because it's a child element. I am using `calc` on this `div` as a workaround.

**Comment by morethanreal** [comment] 2015-06-01 19:01
The reason the `div` is not flexed to take up the available space is because `<my-card>` is not a flex container. See this article for more info on flex box: https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Flexible_boxes

**Comment by zishanj** [comment] 2015-06-01 19:13
I have tried `flex` on my-card also but no luck. As I said, it only works on `primary` elements and for child elements I have to use custom height. It seems to me a browser limitation.

**Comment by cedric-marcone** [comment] 2015-06-08 14:17
Any news on this one ?
The problem is `neon-animated-pages` is always at zero height (because it, understandably for the transitions, uses `position: relative` and its children are forced to `position: absolute`).

Because of that nothing can flex vertically inside of it and it's a pain because we have to resort to js black magic to compute the height of elements inside it :(

Any recommendations on the right way to achieve it ?

**Comment by zishanj** [comment] 2015-06-08 14:49
@cedric-marcone As a temporary workaround, I have used css `height` on `div` like this:

    height: calc(100% - 64px);

here `64px` is the height of `paper-toolbar` if you are using it, otherwise just use `height: 100%` on child div.

**Comment by cedric-marcone** [comment] 2015-06-08 14:56
@zishanj sadly, in our use case, we can't rely on a static height : we can't use the css calc function.

**Comment by cedric-marcone** [comment] 2015-06-12 07:01
For future reference, here is the right way to do it :
```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="import" href="bower_components/polymer/polymer.html">
    <link rel="import" href="bower_components/neon-animation/neon-animated-pages.html">
    <link rel="import" href="bower_components/neon-animation/neon-animations.html">
  </head>
  <body class="fullbleed">

    <dom-module id="test-page">
      <style>
        [outer] > div:nth-child(1) {
          background-color: grey;
          padding: 10px 0;
        }
        [outer] > div:nth-child(2) {
          box-sizing: border-box;
          border: 10px solid red;
          background-color: pink;
        }
      </style>
      <template>
        <div outer class="fit layout vertical">
          <div><content></content></div>
          <div class="flex layout vertical center center-justified">hey flexy !</div>
        </div>
      </template>
      <script>
        Polymer({
          is: 'test-page',

          behaviors: [
            Polymer.NeonAnimatableBehavior
          ],

          properties: {
            animationConfig: {
              type: Object,
              value: function() {
                return {
                  'entry': {
                    name: 'slide-from-right-animation',
                    node: this
                  },
                  'exit': {
                    name: 'slide-left-animation',
                    node: this
                  }
                }
              }
            }
          }
        })
      </script>
    </dom-module>

    <template is="dom-bind">
      <div class="layout vertical fit" on-click="_click">
        <header>HEADER<br>HEADER<br>HEADER<br>HEADER</header>
        <neon-animated-pages id="pages" selected="0" class="flex">
          <test-page>1</test-page>
          <test-page>2<br>2</test-page>
          <test-page>3<br>3<br>3</test-page>
        </neon-animated-pages>
        <footer>FOOTER<br>FOOTER</footer>
      </div>
    </template>

    <script>
      var scope = document.querySelector('template[is="dom-bind"]')
      scope._click = function(e) {
        this.$.pages.selectNext()
      }
    </script>
  </body>
</html>
```

**Comment by morethanreal** [comment] 2015-06-18 22:57
@cedric-marcone It's also possible to make the `<test-page>` itself a flexbox instead of using a `<div>` in the local DOM, ie.

```html
<dom-module id="test-page">
  <style>
    :host {
      @apply(--layout-fit);
      @apply(--layout-vertical);
    }
  </style>
  <template>
    <div><content></content></div>
    <div class="flex layout vertical center center-justified">hey flexy !</div>
  </template>
</dom-module>
```

I am closing this issue, since there is not an action for this repository.

**Closed by morethanreal** 2015-06-18 22:57 UTC
